name: CI
on:
  push:
    branches: main
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/check.yml

  ci-test:
    needs:
      - lint
    name: Build Kernel
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Kernel
      uses: ./
      with:
          kernel-url: https://github.com/onlyu1106/android_kernel_samsung_msm8998
          kernel-branch: pp
          config: greatqlte_chn_open_defconfig
          arch: arm64
          ksu: true
          ksu-version: main
          aosp-gcc: true
          aosp-clang: false
          android-version: 9
          other-clang-url: https://github.com/kdrag0n/proton-clang.git
          other-clang-branch: master
          disable-lto: true
          anykernel3: true
    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifact
        path: path/to/your/kernel/output/*
